[package]
name = "bevy-mandelbrot"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.0"

# Enable a small amount of optimization in debug mode.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in debug mode for dependencies.
[profile.dev.package."*"]
opt-level = 3
